### ISSUE TITLE
Invalid pid file name

### ISSUE THREAD

**Issue by crosspath** [jmoses/foreman#3]
I tried to stop running rails server (pid file is tmp/pids/server.pid).

```
crosspath@linux-nymq:~/RubymineProjects/Obruset> foreman.ruby2.1 restart web
/usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:93:in `initialize': No such file or directory @ rb_sysopen - /tmp/foreman_Obruset.pid (Errno::ENOENT)
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:93:in `open'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:93:in `read_pids'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:72:in `restart'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/cli.rb:32:in `restart'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/bin/foreman:7:in `<top (required)>'
        from /usr/bin/foreman.ruby2.1:23:in `load'
        from /usr/bin/foreman.ruby2.1:23:in `<main>'
```

**Comment by crosspath** [comment]
Another problem: foreman does not start.
```
crosspath@linux-nymq:~/RubymineProjects/Obruset> foreman.ruby2.1 start
18:12:29 web.1     | started with pid 18421
18:12:29 faye.1    | started with pid 18424
/usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:152:in `eof?': Input/output error @ io_fillbuf - fd:7 /dev/pts/6 (Errno::EIO)
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:152:in `block (2 levels) in run'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:149:in `spawn'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:149:in `block in run'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:148:in `chdir'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:148:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:136:in `block in fork_individual'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:135:in `fork'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:135:in `fork_individual'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:125:in `block in fork'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:124:in `upto'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:124:in `fork'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:61:in `block in start'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:60:in `each'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/engine.rb:60:in `start'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/lib/foreman/cli.rb:23:in `start'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/lib64/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/lib64/ruby/gems/2.1.0/gems/foreman_restartable-0.18.0r/bin/foreman:7:in `<top (required)>'
        from /usr/bin/foreman.ruby2.1:23:in `load'
        from /usr/bin/foreman.ruby2.1:23:in `<main>'
18:12:29 faye.1    | process terminated
18:12:29 system    | sending SIGTERM to all processes
```

**Comment by crosspath** [comment]
``
crosspath@linux-nymq:~/RubymineProjects/Obruset> cat Procfile
web: rails s -d
faye: thin start -R faye.ru -p 9292
``
